// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1, arg2) {
  return window['go']['core']['AuthHandler']['ChangePassword'](arg1, arg2);
}

export function GetAutoLockMinutes() {
  return window['go']['core']['AuthHandler']['GetAutoLockMinutes']();
}

export function IsNewUser() {
  return window['go']['core']['AuthHandler']['IsNewUser']();
}

export function Login(arg1) {
  return window['go']['core']['AuthHandler']['Login'](arg1);
}

export function Register(arg1) {
  return window['go']['core']['AuthHandler']['Register'](arg1);
}

export function SetAutoLockMinutes(arg1) {
  return window['go']['core']['AuthHandler']['SetAutoLockMinutes'](arg1);
}

export function Startup(arg1) {
  return window['go']['core']['AuthHandler']['Startup'](arg1);
}
