// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ChangePassword(arg1:string,arg2:string):Promise<void>;

export function IsNewUser():Promise<boolean>;

export function Login(arg1:string):Promise<void>;

export function Register(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
