// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEntry(arg1, arg2, arg3) {
  return window['go']['core']['EntryHandler']['AddEntry'](arg1, arg2, arg3);
}

export function DeleteEntry(arg1) {
  return window['go']['core']['EntryHandler']['DeleteEntry'](arg1);
}

export function ExportToFile() {
  return window['go']['core']['EntryHandler']['ExportToFile']();
}

export function GetEntries(arg1) {
  return window['go']['core']['EntryHandler']['GetEntries'](arg1);
}

export function GetEntryQR(arg1) {
  return window['go']['core']['EntryHandler']['GetEntryQR'](arg1);
}

export function ImportFromFile() {
  return window['go']['core']['EntryHandler']['ImportFromFile']();
}

export function Startup(arg1) {
  return window['go']['core']['EntryHandler']['Startup'](arg1);
}
