// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {context} from '../models';

export function AddEntry(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteEntry(arg1:string):Promise<void>;

export function ExportToFile():Promise<void>;

export function GetEntries(arg1:string):Promise<Array<core.EntryWithCode>>;

export function ImportFromFile():Promise<number>;

export function Startup(arg1:context.Context):Promise<void>;
