// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportFromURI(arg1) {
  return window['go']['core']['ImportHandler']['ImportFromURI'](arg1);
}

export function Startup(arg1) {
  return window['go']['core']['ImportHandler']['Startup'](arg1);
}
